<div class="container">

<h1>Novo Usuários</h1>


<form action="/novo-usuario" method="POST">
	Nome<br>
	<input type="text" class="form-control" name="nome" required><br>

	Email<br>
	<input type="email"  class="form-control" name="email" required><br>

	Senha<br>
	<input type="password" class="form-control" name="senha" required><br><br>

	<button class="btn btn-primary btn-block">Enviar</button>
	
</form>
</div>